fix(node_exporter): correct indent in systemd template
prometheus-community/ansible pull request #163
Opened 2023-07-20 16:21 UTC by tigattack

Before:
![image](https://github.com/prometheus-community/ansible/assets/10629864/f927070d-57c1-4e4b-ab2b-0c09b013f2f2)

After:
![image](https://github.com/prometheus-community/ansible/assets/10629864/55696ae6-e956-4888-be4c-b0395342f797)

2023-07-23 08:21 UTC, SuperQ commented
Looks like this breaks the startup of the `alternative` test. The exporter fails to run.

2023-07-26 14:03 UTC, SuperQ commented on roles/node_exporter/templates/node_exporter.service.j2
> +{% if node_exporter_tls_server_config | length > 0 or node_exporter_http_server_config | length > 0 or node_exporter_basic_auth_users | length > 0 -%}
I think this part of the change is breaking the alternative test.

```suggestion
{% if node_exporter_tls_server_config | length > 0 or node_exporter_http_server_config | length > 0 or node_exporter_basic_auth_users | length > 0 %}
```

2023-07-26 14:04 UTC, SuperQ commented on roles/node_exporter/templates/node_exporter.service.j2
> +{% endif -%}
```suggestion
{% endif %}
```

2023-08-22 02:32 UTC, gardar requested changes
Please rebase

2024-01-15 14:53 UTC, closed without merging