Fix --systemd.collector flags for lower versions
prometheus-community/ansible pull request #208
Opened 2023-08-26 08:28 UTC by haavard

In systemd_exporter 0.5.0, `--systemd.collector` were renamed from `--collector` to `--systemd.collector`.

2023-08-26 08:43 UTC, SuperQ requested changes
Would you please add some molecule tests?

You can see `roles/prometheus/molecule/alternative/tests/test_alternative.py` for a good example of how to do this.

2023-08-26 08:45 UTC, haavard commented
> Would you please add some molecule tests?
> 
> You can see `roles/prometheus/molecule/alternative/tests/test_alternative.py` for a good example of how to do this.

@SuperQ I added these variables to the existing alternative test, which runs on the lower 0.4.0 version of systemd_exporter. The test would fail without the accompanying patch.

2023-08-26 08:54 UTC, SuperQ commented
Yea, I suppose that's ok.

2023-08-26 08:55 UTC, SuperQ approved these changes

2023-08-29 13:58 UTC, gardar approved these changes

2023-08-29 13:58 UTC, merged