pushgateway extra parameters
prometheus-community/ansible pull request #320
Opened 2024-03-22 11:10 UTC by weakcamel

Allow passing in additional parameters for the pushgateway binary

* `pushgateway_web_external_url` - useful when running behind a reverse proxy
* `pushgateway_cli_extra_flags` - additional extra flags for flexibility

Resolves #288

2024-04-09 12:34 UTC, gardar requested changes
Please add the new options to the argument specs as well, they are located under `meta/argument_specs.yml`

2024-04-10 11:41 UTC, weakcamel commented
> Please add the new options to the argument specs as well, they are located under `meta/argument_specs.yml`

Sure thing, done. PTAL

2024-04-10 11:55 UTC, gardar reviewed
LGTM, can you please fix the DCO so that this can be merged?

2024-04-10 12:04 UTC, weakcamel commented
> LGTM, can you please fix the DCO so that this can be merged?

Silly me! of course, done.

2024-06-17 06:41 UTC, edgarasg commented
Can this be merged?

2024-07-31 14:43 UTC, weakcamel commented on roles/pushgateway/defaults/main.yml
> +pushgateway_cli_extra_flags: []
Sorry, I completely lost track of this PR.

Are you sure `config_flags_extra` is the good choice here?

These are not **config** flags, these are flags to pass to the binary, so there's nothing to be consistent with here as far as I can tell.

2024-07-31 15:06 UTC, weakcamel commented on roles/pushgateway/defaults/main.yml
> +pushgateway_cli_extra_flags: []
Done.

2024-07-31 15:16 UTC, weakcamel commented
Changes made as requested (sorry for losing this out of my radar for so long).

Unfortunately there are currently some issues with the CI:
https://github.com/prometheus-community/ansible/actions/runs/10182776539/job/28166214532?pr=320


```
WARNING: Failed to pull docker image "quay.io/ansible/default-test-container:1.10.1". Waiting a few seconds before trying again.
ERROR: Failed to pull docker image "quay.io/ansible/default-test-container:1.10.1".
```

Rebased the changes and trying again.

2024-08-05 16:32 UTC, weakcamel commented
Rebase didn't help and I don't believe those failures are related to my changes.

@gardar @SuperQ could you please have another look?

2024-10-18 17:36 UTC, gardar commented
@weakcamel sorry about the radio silence, was doing some major overhaul of the roles in the background, which has now been merged #425 
We can get this merged if you would be so kind to re-open and rebase this PR.

2025-01-10 17:46 UTC, weakcamel commented
PR reopened and rebased.

2025-01-12 13:29 UTC, SuperQ approved these changes

2025-01-12 14:13 UTC, gardar approved these changes

2025-01-12 14:14 UTC, merged