enhancement(prometheus): support prometheus2 .yml rule file format
prometheus-community/ansible pull request #333
Opened 2024-04-15 11:01 UTC by dpavle

2024-04-15 13:43 UTC, dpavle commented on roles/prometheus/templates/prometheus.yml.j2
> +  - {{ prometheus_config_dir }}/rules/*.rules.yml
Yep, that makes sense.

2024-04-15 14:04 UTC, SuperQ commented
Please also update the updated docs.

2024-04-16 19:59 UTC, SuperQ approved these changes

2024-04-16 21:00 UTC, gardar requested changes
If we want to support both `.rules` and `.yml` as proposed by this PR then both should be listed in the docs and argument specs.

But if we want to drop `.rules` then that should be done clearly with a warning in the preflight.

Also `.yaml` should be supported since both`.yml` and `.yaml` are valid yaml file extensions.

2024-04-17 10:01 UTC, dpavle commented
> If we want to support both `.rules` and `.yml` as proposed by this PR then both should be listed in the docs and argument specs.
> 
> But if we want to drop `.rules` then that should be done clearly with a warning in the preflight.
> 
> Also `.yaml` should be supported since both`.yml` and `.yaml` are valid yaml file extensions.

I'm for removing the old `.rules` format. It's essentially been deprecated [since 2017](https://prometheus.io/blog/2017/06/21/prometheus-20-alpha3-new-rule-format/) and it doesn't work in any recent version of Prometheus as far as I'm aware. 

As for the warning in the preflight, sure, that could be done. I'm just not sure how exactly, do we fail if any `.rules` files are found in `/rules`?  

And yes, `.yaml` should also be supported.

2024-04-17 12:48 UTC, SuperQ commented
We probably want to keep the `*.rules` handling, at least from a configuration loading perspective, around in order to maintain backwards compatibility. Otherwise existing deployments that are pushing yaml to files named `.rules` will break.

2024-04-17 13:39 UTC, gardar commented
> We probably want to keep the `*.rules` handling, at least from a configuration loading perspective, around in order to maintain backwards compatibility. Otherwise existing deployments that are pushing yaml to files named `.rules` will break.

That's why I suggested a error in the preflight, but we could also make that a warning for now and then drop `*.rules` support in the future.
Or we could handle it automatically by adding a task that renames `.rules` to `.yml`

2024-04-18 10:57 UTC, dpavle commented
> > We probably want to keep the `*.rules` handling, at least from a configuration loading perspective, around in order to maintain backwards compatibility. Otherwise existing deployments that are pushing yaml to files named `.rules` will break.
> 
> That's why I suggested a error in the preflight, but we could also make that a warning for now and then drop `*.rules` support in the future. Or we could handle it automatically by adding a task that renames `.rules` to `.yml`

A warning works. If there are any YAML formatted files with the .rules extension there will be a warning message in the preflight and the rule validation will pass normally. On the other hand, if there are any rules in the old .rules format, the warning message will show in the preflight and promtool check validation will catch them and fail in a later step.

2024-06-06 17:20 UTC, gardar approved these changes
LGTM

2024-10-30 16:04 UTC, gardar commented
@dpavle any chance you could refactor this so that we can get it merged?

2024-10-30 17:40 UTC, dpavle commented
> @dpavle any chance you could refactor this so that we can get it merged?

sure, I'll take a look at it

2024-10-31 16:18 UTC, gardar commented
@SuperQ any outstanding issues or are we good to go?

2024-10-31 16:20 UTC, gardar approved these changes

2024-10-31 16:25 UTC, SuperQ approved these changes
Yup, LGTM

2024-10-31 16:33 UTC, merged