minor: bump support for ansible from v2.16.* to v2.17.*
prometheus-community/ansible pull request #414
Opened 2024-09-07 13:44 UTC by andygrunwald

## Context

Fix #386

## Last version bump

The last version bump was in https://github.com/andygrunwald/ansible/commit/2e0a30de1aecf46d046e24e2e4a9bff454696305
It is not clear to me, why the version was set down to 2.16.* (from 2.17)

A lot of changes has been between Ansible v2.16.10 and v2.17.3, see https://github.com/ansible/ansible/compare/v2.16.10...v2.17.3

## Ansible version

The following ansible version is used with v0.17.1 of the ansible role `prometheus.prometheus`:

```
ansible [core 2.17.3]
  config file = None
  configured module search path = ['/Users/andy.grunwald/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/10.3.0/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/andy.grunwald/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.5 (main, Aug  6 2024, 19:08:49) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/Cellar/ansible/10.3.0/libexec/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

2024-09-07 14:20 UTC, andygrunwald commented
The GitHub Action workflow failure in `Ansible CI / ansible-test-sanity / sanity-stable-2.9 (pull_request) ` is due to a non available docker image that can't be pulled. The failure is not PR / change related.

PRs like https://github.com/prometheus-community/ansible/pull/411 may a solution to this.

2024-09-28 12:44 UTC, gardar commented
> ## Context
> 
> Fix #386
> 
> ## Last version bump
> 
> The last version bump was in https://github.com/prometheus-community/ansible/commit/2e0a30de1aecf46d046e24e2e4a9bff454696305
> It is not clear to me, why the version was set down to 2.16.* (from 2.17)

At that time 2.17 was unreleased, but those two are essentially equal, the operator "less than" `2.17` and "less than or equal to" `2.16.99`
 
The reason for the change was due to how we are using the supported versions to do testing in the CI, but it has the same effect for the user.

Anyways, thanks for the PR, can you rebase?

2024-09-29 06:26 UTC, andygrunwald commented
@gardar Rebased.

2024-09-29 13:51 UTC, gardar requested changes
I think we need to exclude 2.17 from almalinux-8, since [2.17 is not supported on el8 based distros](https://github.com/ansible/ansible/issues/83357#issuecomment-2146361492).

You can do so by adding it here:

https://github.com/prometheus-community/ansible/blob/15369b7c2e969cf1caffca6f5899055e47286da8/.config/molecule/config.yml#L75-L90

2024-09-30 05:38 UTC, andygrunwald commented
@gardar Excluded in https://github.com/prometheus-community/ansible/pull/414/commits/e0d0aa4ba65f5c3fc23feefadd81609096972448

2024-09-30 05:41 UTC, SuperQ approved these changes

2024-09-30 09:34 UTC, gardar approved these changes

2024-09-30 09:35 UTC, merged