feat: move naive assertion to common role
prometheus-community/ansible pull request #443
Opened 2024-10-29 13:02 UTC by zhan9san

If this proposal is accepted, I'll update all other roles

2024-10-29 14:57 UTC, SuperQ approved these changes

2024-10-29 15:00 UTC, gardar requested changes
Thanks! Please go ahead with applying the change across all the roles

2024-10-29 15:37 UTC, zhan9san commented
Done. It's ready for review

2024-10-29 17:22 UTC, gardar requested changes

2024-10-29 17:22 UTC, gardar commented on roles/smartctl_exporter/tasks/preflight.yml
Don't forget to remove the naive assertion task here

2024-10-30 01:54 UTC, zhan9san commented on roles/smartctl_exporter/tasks/preflight.yml
Good point. It's removed.

2024-10-30 02:01 UTC, zhan9san commented
> I wonder if this assert should be added to the cadvisor role too.

I should list cadvisor in the description.

It is not added intentionally. Because it is not in standard format.

```shell
$ docker run --rm -it gcr.io/cadvisor/cadvisor --help | grep -E 'listen|port'
    	Only report docker containers in addition to root stats
  -listen_ip string
    	IP to listen on, defaults to all IPs
  -port int
    	port to listen (default 8080)
```

`node_exporter` and others is in this format, `--web.listen-address=:9100`.

2024-10-31 15:40 UTC, gardar approved these changes
LGTM

2024-10-31 15:41 UTC, merged