enhancement: Check that TLS cert and key can be read
prometheus-community/ansible pull request #55
Opened 2023-03-07 18:02 UTC by volcan01010

## Summary

This pull request adds an extra assertion to the preflight checks to confirm that the `node_exporter` process has read permission on the TLS key and certificate.

## Background

When we tried setting up the node exporter with TLS we found that the playbook ran successfully but that the node exporter was not running on the target server.
The error messages from `systemctl status node_exporter` did not contain useful information.
Eventually we traced the problem to the TLS certificate having `r-------- root root` permissions and therefore not being accessible to the `node-exp` system account.
Adding this extra check will prevent this happening to others.

## To test

I have not updated the `molecule` tests as there were no equivalent tests on the other preflight assertions. To trigger the assertion manually, you can run `chmod 0000 /path/to/your/tls.key` and then apply the role. It should fail during the preflight tests.

Thank you for your work on this role!

Note: This merge request has been migrated from the previous repository at https://github.com/cloudalchemy/ansible-node-exporter/pull/264

2023-03-08 10:01 UTC, gardar commented
@volcan01010 Please fix CI errors

2023-03-13 17:30 UTC, volcan01010 commented
Hi, the CI is passing now.

2023-03-13 18:20 UTC, gardar requested changes
#65

2023-03-13 18:20 UTC, gardar commented on roles/node_exporter/tasks/preflight.yml
> +      become_user: "{{ _node_exporter_system_user }}"
```suggestion
      become_user: "{{ node_exporter_system_user }}"
```

2023-03-13 18:20 UTC, gardar commented on roles/node_exporter/tasks/preflight.yml
> +          {{ _node_exporter_system_user }} system user does not have read
```suggestion
          {{ node_exporter_system_user }} system user does not have read
```

2023-03-17 14:44 UTC, gardar requested changes

2023-03-17 14:44 UTC, gardar commented on roles/node_exporter/tasks/preflight.yml
> +      become_user: "{{ _node_exporter_system_user }}"
```suggestion
      become_user: "{{ node_exporter_system_user }}"
```

2023-03-22 12:57 UTC, gardar commented
Looking at this I don't think this approach is totally correct, you are trying to become a user that does not exist yet. The node_exporter user is created in the install steps that are executed after the preflight.
(It would work fine if you already executed the role, or manually created the user, but fail in every other case.)

It could be a bit tricky to achieve this. You would need to check both the name of the owner/group of the file and the permissions of the file, and make sure the node exporter user falls within that scope.

2023-04-17 11:23 UTC, volcan01010 commented
Ah, yes.  Good point.  I made the changes to the role on my own machine after previously running the script and creating the user.

This request was only meant to be a small tweak to provide a minor improvement, and I am not able to do much deeper work.  I will close the request.

Thanks for your time reviewing the request and to the wider team for keeping the Node Exporter role alive.

2023-04-17 11:23 UTC, closed without merging