Lie add tags support for included tasks
prometheus-community/ansible pull request #87
Opened 2023-04-17 10:05 UTC by laurent-indermuehle

This is a PR to fix #86

I think `import_tasks` should be prefered. But I don't want to impose my choice.

2023-04-17 17:27 UTC, gardar commented
Thanks for the PR.
You are correct that currently the tags do very little, since they only apply to the include itself and the tags are missing from the included tasks.
The roles previously used the now deprecated `include` module and I had not tested the tags after migrating to `include_tasks`.

Rather than applying the tags to everything I would prefer that the tags were added to the relevant tasks instead, as applying the tags to the whole import/include will run some tasks that don't necessarily need to run.

2023-04-17 17:30 UTC, gardar requested changes

2023-04-17 17:30 UTC, gardar commented on changelogs/fragments/fix86_apply_tags.yml
> +  - all roles - Fix tags to enable the execution of a specific tasks file as intended.
This is not needed as the changelog is automatically generated from the PR title, please update the title with the relevant tag.
See here: https://github.com/prometheus-community/ansible/blob/main/CONTRIBUTING.md#releases

2023-04-25 11:26 UTC, laurent-indermuehle commented
I discovered, thanks to the bot, that my commits must be signed-off. I just did. 

I think the contributors guide is lacking this information. But I appreciate the effort you make to automate quality control.

Ready for review.

2023-04-27 07:42 UTC, laurent-indermuehle commented
I fixed a yaml indentation (thanks to ansible-lint, I love this tool). But I got trapped again by the signed-off of my commit. This is not documented in the contributors guide either.
Could you please remove this constrain or explain how to configure this repository to always signed-off commits?

Also, I did what your requested in your code review and resolved the comment, but this PR is still marked "requested changes". Do you know why?

2023-05-03 12:03 UTC, gardar approved these changes

2023-05-03 12:03 UTC, merged